backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

#publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Название", name: "title", widget: "string"}
      - {label: "Дата публикации", name: "date", widget: "datetime"}
      - {label: "Картинка", name: "featured", widget: "image", required: false}
      - {label: "Категории", name: "categories", widget: "list", required: true}
      - {label: "Теги", name: "tags", widget: "list", required: true}
      - {label: "Текст", name: "body", widget: "markdown"}